version = 5.6.0
archive_dir = /etc/letsencrypt/archive/chat.redmemoria.net
cert = /etc/letsencrypt/live/chat.redmemoria.net/cert.pem
privkey = /etc/letsencrypt/live/chat.redmemoria.net/privkey.pem
chain = /etc/letsencrypt/live/chat.redmemoria.net/chain.pem
fullchain = /etc/letsencrypt/live/chat.redmemoria.net/fullchain.pem
[renewalparams]
account = 54807313356ccb0d5908af1a84bab670
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
chat.redmemoria.net = /var/www/certbot
